import React from "react";
import { Metadata } from "next";
import { Navbar } from "./components/navbar";
// import { Footer } from "../components/footer";
 // import {Footer} from "./components/footer";
export const metadata: Metadata = {
  title: "This is demo Layout",
  description: "Generated by create next app",
};

const DemoLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      <div className="flex justify-center  items-center">
        <Navbar />
      </div>
      {children}
      {/* <Footer/> */}
    </div>
  );
};

export default DemoLayout;
